[package]
name = "pipelock-config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "YAML config loading + hot-reload for pipelock-rs."

[dependencies]
pipelock-core = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
arc-swap = { workspace = true }

[lints]
workspace = true
